image: node:15.11.0

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

npm-test:
  stage: test
  script:
    - echo "Install npm..."
    - npm install
    - echo "Run npm test..."
    - npm test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
